# Minimal

# Configurations
hideui singleuser,hints,arrows,label,badges
resolution 1920 1080
icons_dir /icons
banner background.png
banner_scale fillscreen
selection_big   selection_big.png
selection_small selection_small.png
showtools shutdown

# Menu Entry
#dont_scan_files + bootx64.efi
#dont_scan_dirs + boot/